name: mma-test
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip:
      - dash==2.17.0
      - keras==3.3.3
      - matplotlib==3.9.0
      - numpy==1.26.4
      - pandas==2.2.2
      - plotly==5.22.0
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - tensorflow==2.16.1
      - trimap==1.1.4
      - pacmap==0.7.3
      - umap-learn==0.5.6
